{
 "title": "api",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API UP",
   "type": "stat",
   "description": "Verifica se a API está recebendo requisições",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"url-shorter-api-health-check\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL's encurtadas",
   "type": "stat",
   "description": "Total de url's encurtadas",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{job=\"url-shorter-api\", http_request_method=\"POST\", http_response_status_code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tentativas de Reencurtar URL",
   "type": "stat",
   "description": "Total de tentativas para encurtar uma url já encurtada",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{job=\"url-shorter-api\", http_request_method=\"POST\", http_response_status_code=\"409\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL's Não Encurtadas",
   "type": "stat",
   "description": "Total de URL's não encurtadas por estarem mal formatadas",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{job=\"url-shorter-api\", http_request_method=\"POST\", http_response_status_code=\"400\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL's Encurtadas Enviadas Fila",
   "type": "stat",
   "description": "Total de URL's encurtadas que foram enviadas para a fila de pós-processamento",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "url_shorter_api_urls_encurtadas_enviadas_fila_processamento_total{job=\"url-shorter-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}