{
 "title": "consumer",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "URL's Encurtadas Recuperadas Fila",
   "type": "stat",
   "description": "Total de url's que foram recuperadas da fila de pós-processamento",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum_over_time(url_shorter_consumer_urls_recuperada_fila_processamento_total{job=\"url-shorter-consumer\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL's Rejeitadas Fila",
   "type": "stat",
   "description": "Total de url's que foram rejeitadas durante o pós-processamento pois, não possuem formato válido",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum_over_time(url_shorter_consumer_urls_rejeitas_total{job=\"url-shorter-consumer\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL's Fila Falha Pós Processamento",
   "type": "stat",
   "description": "Total de URL's que estão na fila de falha pós-processamento",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\r\n| scope \"messages_ready\"",
     "url": "/queues/url-shorter/url.shorter.api.v1.shorting-failure",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "URL's Recuperadas Fila Pós-Processamento Sucesso",
   "type": "stat",
   "description": "Total de url's que foram processadas com sucesso da fila de pós-processamento",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum_over_time(url_shorter_consumer_urls_processadas_total{job=\"url-shorter-consumer\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}