receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        value: "name"
        action: insert

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus-container:9090/api/v1/write"
    tls:
      insecure: true
  loki:
    endpoint: http://loki-container:3100/loki/api/v1/push
    tls:
      insecure: true
  otlphttp/tempo:
    endpoint: http://tempo-container:4318
    tls:
      insecure: true
  debug:

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
