global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "url-shorter-api-health-check"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://url-shorter-api-container:8080/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-container:9115
